; hw.pki-on-box HMI firmware (WeAct G474CEU TRNG USB HID streamer)

[platformio]
default_envs = weact_g474ceu

[env]
monitor_speed    = 115200
upload_protocol  = cmsis-dap
debug_tool       = cmsis-dap
lib_archive      = no
board_build.boards_dir = boards

[env:weact_g474ceu]
platform    = https://github.com/platformio/platform-ststm32.git
framework   = stm32cube
board       = weact_g474ceu

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32G474xx
    -DCUSTOM_HID_EPIN_SIZE=0x40
    -DCUSTOM_HID_EPOUT_SIZE=0x40
    -DUSBD_CUSTOMHID_OUTREPORT_BUF_SIZE=64
    -DUSBD_CUSTOM_HID_REPORT_DESC_SIZE=22
    -I${PROJECT_DIR}/src
    -I${PROJECT_DIR}/lib/usb_dfu/Core/Inc
    -I${PROJECT_DIR}/lib/usb_dfu/Class/CustomHID/Inc

build_src_filter =
    +<${PROJECT_DIR}/boards/startup_stm32g474xx.s>
    +<${PROJECT_DIR}/src/main.c>
    +<${PROJECT_DIR}/src/SystemClock_Config.c>
    +<${PROJECT_DIR}/src/usbd_conf.c>
    +<${PROJECT_DIR}/src/usbd_desc.c>
    +<${PROJECT_DIR}/src/usbd_customhid.c>

lib_ignore =
    STM32_USB_Device_Library-Core
    STM32_USB_Device_Library-CustomHID
