;
; hw.pki-on-box — HMI firmware (STM32H750VBT6 TRNG streamer)
;

[platformio]
default_envs = hmi

[env]
monitor_speed    = 115200
upload_protocol  = cmsis-dap
debug_tool       = cmsis-dap
lib_archive      = no

[env:hmi]
platform    = https://github.com/platformio/platform-ststm32.git
framework   = stm32cube
board       = genericSTM32H750VB

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32H750xx

build_src_filter =
    +<src/*.c>

lib_extra_dirs =
    lib/
